language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
cache: pip
before_install:
  - pip install -U pip
  - pip install coveralls
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r awxinventory/test/test-requirements.txt
script:
  - coverage run --omit awxinventory/test/ awxinventory/test/test_awxInventory.py
  - coverage xml --omit awxinventory/test/
after_success:
  - coveralls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml
