language: python
python:
  - "3.6"
cache: pip
before_install:
  - pip install -U pip
  - pip install coveralls
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r test/test-requirements.txt
script:
  - coverage run --omit test/ test/test_awxInventory.py
  - ls
after_success:
  - coveralls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
